// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN4LhnxP2EjhYfakiC4_Qznxcd4W1v08Q',
    appId: '1:983203290530:web:80058ee1fbed3eabb9a6fb',
    messagingSenderId: '983203290530',
    projectId: 'yousafe-cccc4',
    authDomain: 'yousafe-cccc4.firebaseapp.com',
    storageBucket: 'yousafe-cccc4.appspot.com',
    measurementId: 'G-10DCEY6XTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJjP1rAML-CNMxmPHQuQLnqxjg7E8TUp0',
    appId: '1:983203290530:android:1b5d4f06f70c28fcb9a6fb',
    messagingSenderId: '983203290530',
    projectId: 'yousafe-cccc4',
    storageBucket: 'yousafe-cccc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtmbgpysQ2z7QYGfWMhTLYwuMBRtYwA2c',
    appId: '1:983203290530:ios:be9bec7f01a0d4aab9a6fb',
    messagingSenderId: '983203290530',
    projectId: 'yousafe-cccc4',
    storageBucket: 'yousafe-cccc4.appspot.com',
    androidClientId: '983203290530-04ud12vt308ltj7lmp1ksvm3qpumf1ef.apps.googleusercontent.com',
    iosClientId: '983203290530-1fa2jbhs5bj303875qpib0k7lcmrcdrs.apps.googleusercontent.com',
    iosBundleId: 'com.yousafeapp.yousafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtmbgpysQ2z7QYGfWMhTLYwuMBRtYwA2c',
    appId: '1:983203290530:ios:be9bec7f01a0d4aab9a6fb',
    messagingSenderId: '983203290530',
    projectId: 'yousafe-cccc4',
    storageBucket: 'yousafe-cccc4.appspot.com',
    androidClientId: '983203290530-04ud12vt308ltj7lmp1ksvm3qpumf1ef.apps.googleusercontent.com',
    iosClientId: '983203290530-1fa2jbhs5bj303875qpib0k7lcmrcdrs.apps.googleusercontent.com',
    iosBundleId: 'com.yousafeapp.yousafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN4LhnxP2EjhYfakiC4_Qznxcd4W1v08Q',
    appId: '1:983203290530:web:24e0d57446e8101db9a6fb',
    messagingSenderId: '983203290530',
    projectId: 'yousafe-cccc4',
    authDomain: 'yousafe-cccc4.firebaseapp.com',
    storageBucket: 'yousafe-cccc4.appspot.com',
    measurementId: 'G-9HRH3QKVVV',
  );

}